version: "3.4"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/user/app
      - /user/app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
